export const QUESTIONS = [
  { id: 0, a: { emoji: '🍔', text: '평생 배달음식만 먹기', seed: 58 }, b: { emoji: '🍚', text: '평생 집밥만 먹기', seed: 42 } },
  { id: 1, a: { emoji: '💰', text: '월급 두 배, 야근도 두 배', seed: 22 }, b: { emoji: '⏰', text: '월급 그대로, 정시 칼퇴', seed: 78 } },
  { id: 2, a: { emoji: '☕', text: '커피 없이 하루 살기', seed: 65 }, b: { emoji: '📱', text: '폰 없이 하루 살기', seed: 35 } },
  { id: 3, a: { emoji: '☀️', text: '평생 여름만', seed: 30 }, b: { emoji: '❄️', text: '평생 겨울만', seed: 70 } },
  { id: 4, a: { emoji: '🌅', text: '완벽한 아침형 인간 되기', seed: 45 }, b: { emoji: '🌙', text: '완벽한 밤형 인간 되기', seed: 55 } },
  { id: 5, a: { emoji: '🚇', text: '매일 지옥철 30분', seed: 72 }, b: { emoji: '🚶', text: '매일 걸어서 1시간', seed: 28 } },
  { id: 6, a: { emoji: '💵', text: '지금 당장 10억', seed: 61 }, b: { emoji: '📅', text: '평생 매달 300만원', seed: 39 } },
  { id: 7, a: { emoji: '🤝', text: '친구 적지만 깊은 사이', seed: 55 }, b: { emoji: '🎉', text: '친구 많지만 가벼운 사이', seed: 45 } },
  { id: 8, a: { emoji: '🍜', text: '평생 한 가지 음식만 먹기', seed: 40 }, b: { emoji: '🍱', text: '매일 다른 음식, 근데 맛없음', seed: 60 } },
  { id: 9, a: { emoji: '🏠', text: '재택근무, 매일 똑같은 하루', seed: 68 }, b: { emoji: '🏢', text: '출근, 맛집 많은 회사 근처', seed: 32 } },
  { id: 10, a: { emoji: '🧳', text: '혼자 떠나는 자유여행', seed: 52 }, b: { emoji: '👥', text: '다 같이 가는 단체여행', seed: 48 } },
  { id: 11, a: { emoji: '⏪', text: '과거로 돌아가서 다시 살기', seed: 44 }, b: { emoji: '🔮', text: '미래를 살짝 미리 보기', seed: 56 } },
  { id: 12, a: { emoji: '💰', text: '연봉이 공개되는 삶', seed: 30 }, b: { emoji: '🎂', text: '나이가 공개되는 삶', seed: 70 } },
  { id: 13, a: { emoji: '👔', text: '완벽한 상사 + 힘든 업무', seed: 38 }, b: { emoji: '😌', text: '편한 업무 + 별로인 상사', seed: 62 } },
  { id: 14, a: { emoji: '🗓️', text: '주 4일제, 연봉 20% 감소', seed: 81 }, b: { emoji: '💼', text: '주 5일제, 연봉 그대로', seed: 19 } },
  { id: 15, a: { emoji: '🍰', text: '단 음식 평생 금지', seed: 35 }, b: { emoji: '🧂', text: '짠 음식 평생 금지', seed: 65 } },
  { id: 16, a: { emoji: '🌶️', text: '매운맛 참기', seed: 40 }, b: { emoji: '☕', text: '커피 끊기', seed: 60 } },
  { id: 17, a: { emoji: '🍗', text: '치킨 없는 삶', seed: 20 }, b: { emoji: '🍜', text: '라면 없는 삶', seed: 80 } },
  { id: 18, a: { emoji: '🍚', text: '평생 한식만', seed: 45 }, b: { emoji: '🍝', text: '평생 양식만', seed: 55 } },
  { id: 19, a: { emoji: '🍽️', text: '뷔페 무제한 이용권', seed: 70 }, b: { emoji: '🍣', text: '오마카세 1회 이용권', seed: 30 } },
  { id: 20, a: { emoji: '🌅', text: '아침 안 먹기', seed: 62 }, b: { emoji: '🌙', text: '저녁 안 먹기', seed: 38 } },
  { id: 21, a: { emoji: '🏪', text: '편의점 음식만 먹기', seed: 25 }, b: { emoji: '🍱', text: '학교 급식만 먹기', seed: 75 } },
  { id: 22, a: { emoji: '🥤', text: '물 대신 탄산수만', seed: 55 }, b: { emoji: '🍵', text: '커피 대신 녹차만', seed: 45 } },
  { id: 23, a: { emoji: '🍮', text: '디저트 평생 금지', seed: 48 }, b: { emoji: '🍺', text: '술 평생 금지', seed: 52 } },
  { id: 24, a: { emoji: '🏆', text: '명예 얻기', seed: 30 }, b: { emoji: '💰', text: '부 얻기', seed: 70 } },
  { id: 25, a: { emoji: '💳', text: '통장 잔고 공개되기', seed: 28 }, b: { emoji: '🔍', text: '검색 기록 공개되기', seed: 72 } },
  { id: 26, a: { emoji: '🎉', text: '로또 당첨, 소문남', seed: 45 }, b: { emoji: '🤐', text: '로또 당첨, 비밀 유지', seed: 55 } },
  { id: 27, a: { emoji: '🐷', text: '무조건 저축하기', seed: 58 }, b: { emoji: '🎊', text: '현재를 즐기기', seed: 42 } },
  { id: 28, a: { emoji: '🏠', text: '큰 집, 대출 있음', seed: 40 }, b: { emoji: '🏡', text: '작은 집, 대출 없음', seed: 60 } },
  { id: 29, a: { emoji: '🏙️', text: '월세 살지만 도심', seed: 53 }, b: { emoji: '🌳', text: '자가살지만 외곽', seed: 47 } },
  { id: 30, a: { emoji: '👜', text: '명품 한 번 사기', seed: 35 }, b: { emoji: '✈️', text: '그 돈으로 여행가기', seed: 65 } },
  { id: 31, a: { emoji: '📈', text: '주식에 몰빵하기', seed: 25 }, b: { emoji: '🏦', text: '예금만 하기', seed: 75 } },
  { id: 32, a: { emoji: '🎨', text: '비싼 취미 갖기', seed: 50 }, b: { emoji: '💵', text: '취미 없이 저축하기', seed: 50 } },
  { id: 33, a: { emoji: '⏰', text: '하루 26시간 살기', seed: 66 }, b: { emoji: '⏱️', text: '하루 22시간 살기', seed: 34 } },
  { id: 34, a: { emoji: '⏩', text: '시간 빨리 감기 능력', seed: 38 }, b: { emoji: '⏪', text: '시간 되감기 능력', seed: 62 } },
  { id: 35, a: { emoji: '🔁', text: '인생 두 번 살기(기억 리셋)', seed: 54 }, b: { emoji: '🧠', text: '인생 한 번, 기억은 유지', seed: 46 } },
  { id: 36, a: { emoji: '🎓', text: '20대로 돌아가기', seed: 58 }, b: { emoji: '😊', text: '지금 이대로 살기', seed: 42 } },
  { id: 37, a: { emoji: '🔄', text: '매일 완전히 똑같은 하루', seed: 20 }, b: { emoji: '🎲', text: '매일 예측 불가능한 하루', seed: 80 } },
  { id: 38, a: { emoji: '🧍', text: '평생 지금 이 나이로 살기', seed: 35 }, b: { emoji: '📆', text: '자연스럽게 나이 들기', seed: 65 } },
  { id: 39, a: { emoji: '😴', text: '잠을 안 자도 안 피곤함', seed: 72 }, b: { emoji: '🍕', text: '아무리 먹어도 안 찜', seed: 28 } },
  { id: 40, a: { emoji: '💡', text: '하루 정전(전기 없음)', seed: 48 }, b: { emoji: '🚿', text: '하루 단수(물 없음)', seed: 52 } },
  { id: 41, a: { emoji: '🛌', text: '매일 늦잠 자는 삶', seed: 56 }, b: { emoji: '🌄', text: '매일 일찍 일어나는 삶', seed: 44 } },
  { id: 42, a: { emoji: '🍯', text: '칼퇴 못 하는 꿀직장', seed: 40 }, b: { emoji: '😮‍💨', text: '야근 없는 힘든 직장', seed: 60 } },
  { id: 43, a: { emoji: '🕵️', text: '적당히 일해도 되는 직장', seed: 45 }, b: { emoji: '🏅', text: '열심히 하면 인정받는 직장', seed: 55 } },
  { id: 44, a: { emoji: '👥', text: '상사가 친구 같은 사이', seed: 35 }, b: { emoji: '🙅', text: '상사와 남남처럼 무관심', seed: 65 } },
  { id: 45, a: { emoji: '📋', text: '매일 회의 3개', seed: 20 }, b: { emoji: '💬', text: '매일 메신저 폭탄 100개', seed: 80 } },
  { id: 46, a: { emoji: '⏰', text: '정시 출근, 정시 퇴근', seed: 70 }, b: { emoji: '🌙', text: '자율 출퇴근, 가끔 야근', seed: 30 } },
  { id: 47, a: { emoji: '❤️', text: '좋아하는 일, 적은 돈', seed: 48 }, b: { emoji: '💵', text: '싫어하는 일, 많은 돈', seed: 52 } },
  { id: 48, a: { emoji: '👑', text: '팀장 되기(책임 커짐)', seed: 30 }, b: { emoji: '🧑‍💻', text: '평사원 유지(편함)', seed: 70 } },
  { id: 49, a: { emoji: '💔', text: '연애 없이 10년', seed: 25 }, b: { emoji: '💌', text: '매년 연애하고 매번 이별', seed: 75 } },
  { id: 50, a: { emoji: '💑', text: '완벽한 연인, 짧은 만남', seed: 40 }, b: { emoji: '🫂', text: '평범한 연인, 긴 만남', seed: 60 } },
  { id: 51, a: { emoji: '🤫', text: '친구가 내 비밀을 다 앎', seed: 45 }, b: { emoji: '🎭', text: '아무도 나를 잘 모름', seed: 55 } },
  { id: 52, a: { emoji: '💍', text: '평생 결혼 안 하기', seed: 35 }, b: { emoji: '👰', text: '무조건 결혼하기', seed: 65 } },
  { id: 53, a: { emoji: '📞', text: '가족과 매일 연락하기', seed: 52 }, b: { emoji: '📅', text: '가족과 한 달에 한 번 연락', seed: 48 } },
  { id: 54, a: { emoji: '🎊', text: '인싸로 살기', seed: 38 }, b: { emoji: '📚', text: '아싸로 살기', seed: 62 } },
  { id: 55, a: { emoji: '👋', text: '전 애인과 친구로 지내기', seed: 30 }, b: { emoji: '🚫', text: '완전히 연락 끊기', seed: 70 } },
  { id: 56, a: { emoji: '💐', text: '소개팅 매주 하기', seed: 42 }, b: { emoji: '🙅‍♂️', text: '소개팅 평생 안 하기', seed: 58 } },
  { id: 57, a: { emoji: '🐶', text: '반려동물 키우기', seed: 75 }, b: { emoji: '🌱', text: '반려식물 키우기', seed: 25 } },
  { id: 58, a: { emoji: '👻', text: '투명인간 되기', seed: 46 }, b: { emoji: '🕊️', text: '하늘을 날기', seed: 54 } },
  { id: 59, a: { emoji: '🧠', text: '마음 읽는 능력', seed: 35 }, b: { emoji: '🔮', text: '미래 보는 능력', seed: 65 } },
  { id: 60, a: { emoji: '🌀', text: '순간이동 능력', seed: 70 }, b: { emoji: '⏸️', text: '시간 정지 능력', seed: 30 } },
  { id: 61, a: { emoji: '🧟', text: '좀비 아포칼립스 생존자 되기', seed: 40 }, b: { emoji: '🚀', text: '우주 이민자 되기', seed: 60 } },
  { id: 62, a: { emoji: '🤖', text: '로봇 집사 얻기', seed: 65 }, b: { emoji: '🪄', text: '마법 지팡이 얻기', seed: 35 } },
  { id: 63, a: { emoji: '🧠', text: '기억력 두 배 되기', seed: 55 }, b: { emoji: '💪', text: '체력 두 배 되기', seed: 45 } },
  { id: 64, a: { emoji: '🗣️', text: '원하는 외국어 다 하기', seed: 72 }, b: { emoji: '🎸', text: '원하는 악기 다 다루기', seed: 28 } },
  { id: 65, a: { emoji: '✈️', text: '평생 무료 비행기', seed: 58 }, b: { emoji: '📺', text: '평생 무료 넷플릭스', seed: 42 } },
  { id: 66, a: { emoji: '🐾', text: '동물과 대화하기', seed: 50 }, b: { emoji: '🌿', text: '식물과 대화하기', seed: 50 } },
  { id: 67, a: { emoji: '🔁', text: '다시 태어나도 지금의 나', seed: 64 }, b: { emoji: '🎭', text: '완전히 다른 사람으로', seed: 36 } },
  { id: 68, a: { emoji: '📵', text: 'SNS 없는 세상', seed: 45 }, b: { emoji: '🚫', text: '광고 없는 세상', seed: 55 } },
  { id: 69, a: { emoji: '📱', text: '화면 깨진 폰 계속 쓰기', seed: 30 }, b: { emoji: '🔋', text: '배터리 반나절짜리 새 폰', seed: 70 } },
  { id: 70, a: { emoji: '📡', text: '와이파이 없이 한 달', seed: 20 }, b: { emoji: '🎬', text: '넷플릭스 없이 한 달', seed: 80 } },
  { id: 71, a: { emoji: '✍️', text: '손으로 필기만 하기', seed: 35 }, b: { emoji: '⌨️', text: '타자로만 치기', seed: 65 } },
  { id: 72, a: { emoji: '🤖', text: 'AI가 내 일 대신 해주기', seed: 48 }, b: { emoji: '🙋', text: '내가 직접, 더 느리게 하기', seed: 52 } },
  { id: 73, a: { emoji: '🔗', text: '모든 계정 하나로 통합', seed: 60 }, b: { emoji: '🔒', text: '모든 정보 완전 비공개', seed: 40 } },
  { id: 74, a: { emoji: '🎮', text: '하루 종일 게임하기', seed: 42 }, b: { emoji: '📺', text: '하루 종일 영상 보기', seed: 58 } },
  { id: 75, a: { emoji: '😊', text: '이모티콘으로만 대화하기', seed: 25 }, b: { emoji: '🔤', text: '텍스트로만 대화하기', seed: 75 } },
  { id: 76, a: { emoji: '🔕', text: '알림 전부 꺼두기', seed: 55 }, b: { emoji: '🔔', text: '알림 전부 켜두기', seed: 45 } },
  { id: 77, a: { emoji: '🏔️', text: '산으로 여행가기', seed: 46 }, b: { emoji: '🌊', text: '바다로 여행가기', seed: 54 } },
  { id: 78, a: { emoji: '🇰🇷', text: '국내여행 열 번 가기', seed: 40 }, b: { emoji: '🌍', text: '해외여행 한 번 가기', seed: 60 } },
  { id: 79, a: { emoji: '🎒', text: '배낭여행(저예산)', seed: 35 }, b: { emoji: '🏖️', text: '호캉스(고예산 한 번)', seed: 65 } },
  { id: 80, a: { emoji: '📋', text: '계획대로 여행하기', seed: 48 }, b: { emoji: '🎲', text: '즉흥적으로 여행하기', seed: 52 } },
  { id: 81, a: { emoji: '🏔️', text: '겨울에 여행 가기', seed: 38 }, b: { emoji: '🏝️', text: '여름에 여행 가기', seed: 62 } },
  { id: 82, a: { emoji: '🏙️', text: '평생 한 도시만 살아보기', seed: 20 }, b: { emoji: '🌆', text: '매년 다른 도시 살아보기', seed: 80 } },
  { id: 83, a: { emoji: '⛺', text: '캠핑하기', seed: 45 }, b: { emoji: '🏨', text: '호텔에서 묵기', seed: 55 } },
  { id: 84, a: { emoji: '🌃', text: '화려한 야경 명소', seed: 58 }, b: { emoji: '🌲', text: '고요한 자연 명소', seed: 42 } },
  { id: 85, a: { emoji: '✈️', text: '비행기 창가석', seed: 68 }, b: { emoji: '💺', text: '비행기 복도석', seed: 32 } },
  { id: 86, a: { emoji: '❄️', text: '눈 오는 날이 좋다', seed: 55 }, b: { emoji: '🌧️', text: '비 오는 날이 좋다', seed: 45 } },
  { id: 87, a: { emoji: '📏', text: '키 크고 가진 것 적음', seed: 35 }, b: { emoji: '💰', text: '키 작고 가진 것 많음', seed: 65 } },
  { id: 88, a: { emoji: '👶', text: '안 늙는 얼굴', seed: 60 }, b: { emoji: '💪', text: '안 아픈 몸', seed: 40 } },
  { id: 89, a: { emoji: '👅', text: '미각을 잃는다', seed: 20 }, b: { emoji: '👃', text: '후각을 잃는다', seed: 80 } },
  { id: 90, a: { emoji: '💇', text: '평생 곱슬머리', seed: 52 }, b: { emoji: '👁️', text: '평생 쌍커풀 없음', seed: 48 } },
  { id: 91, a: { emoji: '💦', text: '땀을 많이 흘린다', seed: 35 }, b: { emoji: '🥶', text: '손발이 늘 시리다', seed: 65 } },
  { id: 92, a: { emoji: '🥵', text: '더위를 잘 탄다', seed: 45 }, b: { emoji: '🥶', text: '추위를 잘 탄다', seed: 55 } },
  { id: 93, a: { emoji: '🧍', text: '하루 종일 서서 일하기', seed: 40 }, b: { emoji: '🪑', text: '하루 종일 앉아서 일하기', seed: 60 } },
  { id: 94, a: { emoji: '📢', text: '목소리가 커진다', seed: 25 }, b: { emoji: '🤫', text: '목소리가 작아진다', seed: 75 } },
  { id: 95, a: { emoji: '🎯', text: '완벽주의자로 살기', seed: 42 }, b: { emoji: '🤷', text: '대충대충 편하게 살기', seed: 58 } },
  { id: 96, a: { emoji: '📋', text: '계획형 인간으로 살기', seed: 55 }, b: { emoji: '🎲', text: '즉흥형 인간으로 살기', seed: 45 } },
  { id: 97, a: { emoji: '💕', text: '모두에게 조금씩 사랑받기', seed: 38 }, b: { emoji: '💝', text: '소수에게 깊이 사랑받기', seed: 62 } },
  { id: 98, a: { emoji: '✅', text: '항상 옳은 말만 하기', seed: 30 }, b: { emoji: '💬', text: '항상 착한 말만 하기', seed: 70 } },
  { id: 99, a: { emoji: '🌟', text: '유명해지지만 자유 없음', seed: 25 }, b: { emoji: '🍃', text: '평범하지만 자유로움', seed: 75 } },
];
